import "../styles/globals.css";
import Head from "next/head";

import {
  EthereumClient,
  w3mConnectors,
  w3mProvider,
} from "@web3modal/ethereum";
import { Web3Modal } from "@web3modal/react";
import { configureChains, createConfig, WagmiConfig } from "wagmi";
import { sepolia, gnosis } from "wagmi/chains";
import Header from "../components/Header/Header";
import Footer from "../components/Footer/Footer";

const chains = [sepolia, gnosis];
const projectId = "2311";

const { publicClient } = configureChains(chains, [w3mProvider({ projectId })]);
const wagmiConfig = createConfig({
  autoConnect: true,
  connectors: w3mConnectors({ projectId, version: 1, chains }),
  publicClient,
});
const ethereumClient = new EthereumClient(wagmiConfig, chains);

export default function App({ Component, pageProps }) {
  return (
    <>
      <WagmiConfig config={wagmiConfig}>
        <Head>
          <title>Big Bad Bug</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/logo.svg" />
        </Head>
        <div className="px-10 fixed top-0 z-50 shadow-md w-full bg-white">
          <Header />
        </div>
        <div className="mt-20">
          <Component {...pageProps} />
        </div>
        <div className="px-10 w-full bg-blue-500 mt-16">
          <Footer />
        </div>
      </WagmiConfig>

      <Web3Modal projectId={projectId} ethereumClient={ethereumClient} />
    </>
  );
}
